### ISSUE TITLE
Crash on Android 11

### ISSUE THREAD

**Issue by grishka** [grishka/Houseclub#1]
I'm on it

**Comment by profilaktor** [comment]
Как скачать вообще? Не нахожу релизов..

**Comment by iprxy** [comment]
Кнопка Releases, справа на главной странице репозиториев:
https://github.com/grishka/Houseclub/releases

**Comment by profilaktor** [comment]
Спасибо!)

**Comment by profilaktor** [comment]
Не пожалейте, пожалуйста, инвайта! 
Что мне нужно сообщить для его получения?
