### ISSUE TITLE
can't talk in a room 

### ISSUE THREAD

**Issue by ahmed-hady-dev** [grishka/Houseclub#104]
the moderator gave me the permission to talk but the mic icon didn't appear beside the raise hand icon

**Comment by CommanderTvis** [comment]
What version do you use?

**Comment by Error-404v2** [comment]
> What version do you use?

1.0.7 
I noticed several things 
- when given the permission to talk I don't go to speakers area 
- people can't hear me
- as mentioned no mic icon appear
- when leave the room and come back there is muted mic icon next to my Avatar and I can't change it

**Comment by ahmed-hady-dev** [comment]
ya you are totally right 👍
