### ISSUE TITLE
Не открывает приложение

### ISSUE THREAD

**Issue by anis-market** [grishka/Houseclub#108]
При попытке загрузки ошибка при синтаксическом анализе пакета.
Андроид 6.0 MRA058K

**Comment by darkzenon** [comment]
> При попытке загрузки ошибка при синтаксическом анализе пакета.
> Андроид 6.0 MRA058K

Minimal version sdk 24 - Android 7.0.
Минимальнач версия андройд - 7.0

You should upgrade Android up to 7 version. Or you can use python version for pc. It is thecsame for listening. 
Вам нужно обновить ос или использовать python библиотеку с компьютера.
