### ISSUE TITLE
I can't find a room for Thai people. I am Thai.

### ISSUE THREAD

**Issue by loser081** [grishka/Houseclub#114]
I don't know if it's a bug or not, but I can't find a Thai room to help fix it. I am Thai, I can't listen to other countries.

**Comment by grishka** [comment]
> I don't know if it's a bug or not

It is not.

**Comment by Titivoot** [comment]
หาห้องคนไทยและติดตามคนในนั้นครับ ถ้าคนที่เราติดตามเข้าห้องไหนเราจะเห็นด้วย

**Comment by grishka** [comment]
Sorry I don't speak squiggles

**Comment by loser081** [comment]
ออครับ

ในวันที่ จ. 22 ก.พ. 2021 18:50 น. Tititvoot Pangrit <
notifications@github.com> เขียนว่า:
