### ISSUE TITLE
очень сильно трещит звук, у кого то получилось исправить?

### ISSUE THREAD

**Issue by alechur1yandexru** [grishka/Houseclub#115]
очень трещит

**Comment by grishka** [comment]
Нет и не получится.

**Comment by zubkow15** [comment]
Ну, к слову, у меня все на 1,06 стало ГОРАЗДО лучше со звуком

**Comment by anbrikzone** [comment]
1.0.6, 1.07 - треск Android 10, OnePlus 7

**Comment by r0manchak** [comment]
Тоже на 1.0.7 трещит, а на 1.0.5 - все ок.
