### ISSUE TITLE
Crackling audio

### ISSUE THREAD

**Issue by Blackwolf14** [grishka/Houseclub#118]
I have installed 1.0.7 version but it doesn't change anything.

**Comment by anbrikzone** [comment]
The same

**Comment by grishka** [comment]
Stop posting these.

**Comment by grishka** [comment]
Stop posting these.

**Comment by Blackwolf14** [comment]
> Stop posting these.

Stop being rude. Do whatever you want. I don't understand Russian language. I didn't know if someone mentioned that before. When I see this title: "1.0.6: Another attempt at fixing that audio crap", I wanted to say this attempt failed. Thats it. I don't intend to cause trouble.

**Comment by anbrikzone** [comment]
If I use bluetooth headphones and try to enter in the room sometimes after restart the app the voice become normal. I didn't figure out in what case exactly.

**Comment by Blackwolf14** [comment]
> If I use bluetooth headphones and try to enter in the room sometimes after restart the app the voice become normal. I didn't figure out in what case exactly.

Mine is working fine now. There is no crackling sound. I don't know what is the different. The mobile phone and app version(1.0.7) is the same. I have Honor 9 Lite. By the way, I don't use bluetooth headphones.

**Comment by nareunart** [comment]
ในวันที่ อ. 23 ก.พ. 2021 19:12 Blackwolf14 ***@***.***>
เขียนว่า:
