### ISSUE TITLE
Как в данном приложении можно найти нужную тему или найти нужную если есть только ссылка на комнату?

### ISSUE THREAD

**Issue by alechur1yandexru** [grishka/Houseclub#121]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel]
 - OS: [e.g. Android 11]
 - Version [e.g. 1.0.7]

**Additional context**

**Comment by Marianna-arch** [comment]
Как установить ?

Пн, 22 лют. 2021 15:47 користувач alechur1yandexru <notifications@github.com>
пише:
