### ISSUE TITLE
Let's discuss about how works unofficial client on ITBeard youtube-channel

### ISSUE THREAD

**Issue by itbeard** [grishka/Houseclub#126]
**Is your feature request related to a problem? Please describe.**
No, it does not. It is about Code-holder :)

**Describe the solution you'd like**
I'm Lex - .net developer and host of ITBeard (АйТиБорода) YouTube show.
I want to invite @grishka to tell my audience about your app and about android-development in general.

**Describe alternatives you've considered**
Just lets do it!

**Additional context**
My telegram: https://t.me/iamitbeard

**Comment by Marianna-arch** [comment]
Unsubscribe

Пн, 22 лют. 2021 17:39 користувач Лёха АйТиБорода <notifications@github.com>
пише:

**Comment by Nefariusmag** [comment]
It's very interesting idea! I would to watch this

**Comment by dusshe5** [comment]
Звук если бы улучшить то в принципе топ. Остальное пока устраивает
