### ISSUE TITLE
Не удается установить на Android 8.0.0 (Honor 7C)

### ISSUE THREAD

**Issue by makklo** [grishka/Houseclub#13]
Все файлы установлены, но при попытке открыть файл release и установить приложение после окна "не требует специальных разрешений" выводит ошибку "приложение не установлено"

**Comment by LionZXY** [comment]
Здравствуйте. Проблемы с установкой APK могу возникать по многим причинам. Чтобы понять какая конкретно проблема у вас необходимо попробовать установить APK с помощью компьютера, чтобы получить сообщение об ошибке.
1. Включите режим разработчика и там включите отладку по usb. Как это сделать можно узнать в Гугле.
2. Установите драйвера для adb на компьютер
3. Далее в консоли на компьютере пропишите `adb install *путь к файлу APK*
4. Ответ приложите к этому issue или создайте новый.

**Comment by TimurC1** [comment]
> Здравствуйте. Проблемы с установкой APK могу возникать по многим причинам. Чтобы понять какая конкретно проблема у вас необходимо попробовать установить APK с помощью компьютера, чтобы получить сообщение об ошибке.
> 
> 1. Включите режим разработчика и там включите отладку по usb. Как это сделать можно узнать в Гугле.
> 2. Установите драйвера для adb на компьютер
> 3. Далее в консоли на компьютере пропишите `adb install _путь к файлу APK_
> 4. Ответ приложите к этому issue или создайте новый.

Можно ещё из сурцов собрать, может сборка не подходит. Я код не смотрел, может там зависимость от Google Play Services, которых нет на EMUI на новых устройствах Huawei. 
(offtop кстати, когда Glitchless сервер вернётся? И не ожидал встретить тут :)

**Comment by LionZXY** [comment]
Игровые сервера glitchless до сих пор работают. Ссылки и явки на старом месте, заходи

**Comment by grishka** [comment]
Уже было исправлено, я в первые релизы не положил 32-битную библиотеку
