### ISSUE TITLE
Raise hand not working, also can't get invite to speak

### ISSUE THREAD

**Issue by noureldinz3r0** [grishka/Houseclub#134]
**Describe the bug**
When I click on raise hand the moderator doesn't get a notification
Also when he send me an invite to speak I don't get a notification, and when I refresh I'm not added to speakers list

**
**Screenshots**
![Screenshot_20210223-004515](https://user-images.githubusercontent.com/79485227/108780083-93b79100-7570-11eb-9b0e-e2188eb28cca.jpg)
![Screenshot_20210223-004056](https://user-images.githubusercontent.com/79485227/108780084-94e8be00-7570-11eb-8508-5bfe9aeab792.jpg)
.

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel]
 - OS: [e.g. Android 11]
 - Version [e.g. 1.0.7]

**Additional context**

**Comment by Error-404v2** [comment]
I have the same problem with and maybe I'll experiment tomorrow with one of my friends being a moderator of a room and see what he gets.

**Comment by Error-404v2** [comment]
These are some observations
- moderator accepts me but my Avatar doesn't go to speakers area 
- there is no mic icon next to the hand
- when I come out of the room (not leaving) and enter again I see muted icon next to my Avatar

**Comment by adnantawakol** [comment]
I think raise hand is working, then the moderator invites you to speak, then you should refresh and accept the request somewhat but the issue is we do not get a request

**Comment by elzahlan** [comment]
It is a network issue in Egypt, you need to use a VPN to be able to accept invites and go to the speakers area

**Comment by adnantawakol** [comment]
Thank you I'll try it
Edit: it works :D

**Comment by Error-404v2** [comment]
> It is a network issue in Egypt, you need to use a VPN to be able to accept invites and go to the speakers area

I do not get prompt to accept the invitation. 

Today, my friend (iPhone user) and I made a room. I could speak and mute my mic, yet when he removed me from the speaker area, he couldn't bring me back.

**Comment by HagarMagdy** [comment]
It worked for me using VPN

**Comment by ghost** [comment]
which vpn did you use?

**Comment by grishka** [comment]
Not an app issue.
