### ISSUE TITLE
More rooms? Search someone? Linked Social Media Features?

### ISSUE THREAD

**Issue by tustoz** [grishka/Houseclub#137]
**Is your feature request related to a problem? Please describe.**
yes, Is it possible to create a new room feature, search for the name of the person we want to follow? and connect our other social media accounts?

**Describe the solution you'd like**
make new settings page for connect our social media account, and one searchbox on top of recommended room list for search someone you want.

**Screenshots**
<img src="https://find-model.jp/insta-lab/wp-content/uploads/2021/02/clubhouse-profile-1.png" alt="Clubhouse Settings" />
![searchbox](https://user-images.githubusercontent.com/76657906/108886136-2f153880-763b-11eb-8cdd-58f46c54b38f.JPG)

I really appreciate you if you can add this feature, by the way you are amazing

**Comment by msizaky16** [comment]
> That part of the API is marked as "unstable" in that python project
https://github.com/grishka/Houseclub/issues/116#issuecomment-783262781

**Comment by oceanchinatownredpie** [comment]
I would like it too!

**Comment by NAN1985** [comment]
😆
