### ISSUE TITLE
Error loading daya

### ISSUE THREAD

**Issue by feakuru** [grishka/Houseclub#14]
![IMG_20210220_163001_617](https://user-images.githubusercontent.com/14169434/108597214-eb9b9f80-7398-11eb-9374-aaa612a962c2.jpg)
Pic related. The device is Honor 20.

**Comment by lautsevich** [comment]
The same issue![Screenshot_20210220_182845_me.grishka.houseclub.jpg](https://user-images.githubusercontent.com/196445/108600698-ac297f00-73a9-11eb-8696-0c438b6b0ae3.jpg)

Android 10 / Huawei P30 Lite

**Comment by lautsevich** [comment]
It works after app reloading. 

![Screenshot_20210220_183210_me.grishka.houseclub.jpg](https://user-images.githubusercontent.com/196445/108600758-075b7180-73aa-11eb-8fe9-0286d58afaef.jpg)

But... I see this after trying to open user profile

![Screenshot_20210220_183326_me.grishka.houseclub.jpg](https://user-images.githubusercontent.com/196445/108600809-29ed8a80-73aa-11eb-8236-d964a5e3ee6c.jpg)

**Comment by staser** [comment]
That was an error with the API. (Error loading data)

**Comment by tossha** [comment]
Getting the same error when trying to view my profile. Huawei P30.

**Comment by HiHat** [comment]
Same registration issue on Samsung Galaxy S9
