### ISSUE TITLE
I can't talk, I can't ask for anything, I just enter rooms only without searching for friends or rooms and I can't change my avatar 

### ISSUE THREAD

**Issue by muhammedabohalima** [grishka/Houseclub#148]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel]
 - OS: [e.g. Android 11]
 - Version [e.g. 1.0.7]

**Additional context**

**Comment by olenenok-ovi** [comment]
Тоже. Сейчас стоит версия 1.0.7 - пока  только слушаю - говорить не могу. Жду релиз :)

**Comment by grishka** [comment]
Я открыт для пулл-реквестов ;)

**Comment by olenenok-ovi** [comment]
Это клёво, но я тестер :)))
