### ISSUE TITLE
"Joining rooms from said list and by direct links" - how does it works?

### ISSUE THREAD

**Issue by spbroma** [grishka/Houseclub#149]
**Problem**
I can't find ability to:

- find people by username
- join room by link
- open links, like https://ios.joinclubhouse.com/event/xxxxxx via this app

**Screenshots**
<img src="https://user-images.githubusercontent.com/1898310/108982265-a6c87f00-769e-11eb-9350-7c5353c02ab4.png" alt="" width="500"/>

<img src="https://user-images.githubusercontent.com/1898310/108981145-7f24e700-769d-11eb-81bd-74509b95d8b9.jpg" alt="" width="200"/> <img src="https://user-images.githubusercontent.com/1898310/108981146-7fbd7d80-769d-11eb-9595-0b02789590b7.jpg" alt="" width="200"/>

**Comment by impozzible** [comment]
Well, I am able to join rooms with links

**Comment by impozzible** [comment]
Concerning the search feature, someone has implemented that, you can check pull request to see the implementation, I don't know why it's yet to be  accepted though but it works fine.

**Comment by spbroma** [comment]
> Well, I am able to join rooms with links

Could you describe your sequence of actions? In my case it looks following:

1. Click on link,
2. It opens clubhouse site with button "open in app"
3. Click on "open in app" and nothing happens

**My configuration:**

- Samsung Galaxy S10
- Android 11, OneUI 3.0
- Houseclub 1.0.7

**Comment by impozzible** [comment]
1. Click on link https://www.joinclubhouse.com/room/M8YN5bam
2. It asks if you want to open with HouseClub app or Chrome
3. Click HouseClub and it aks if you want to join room
4. Click Join, and room is joined

**Comment by impozzible** [comment]
> **Problem**
> I can't find ability to:
> 
>     * find people by username
> 
>     * join room by link
> 
>     * open links, like https://ios.joinclubhouse.com/event/xxxxxx via this app
> 
> 
> **Screenshots**
> <img alt="" width="500" src="https://user-images.githubusercontent.com/1898310/108982265-a6c87f00-769e-11eb-9350-7c5353c02ab4.png">
> 
> <img alt="" width="200" src="https://user-images.githubusercontent.com/1898310/108981145-7f24e700-769d-11eb-81bd-74509b95d8b9.jpg"> <img alt="" width="200" src="https://user-images.githubusercontent.com/1898310/108981146-7fbd7d80-769d-11eb-9595-0b02789590b7.jpg">

I am guessing you are using events links, those are different from room links.

**Comment by SaadAssa** [comment]
Event links can work but the event need to be active, if the rooms isn't open anymore you'll be redirected to the clubhouse website (just in case: make sure to install the latest version of the apk)

**Comment by spbroma** [comment]
> 1. Click on link https://www.joinclubhouse.com/room/M8YN5bam
> 2. It asks if you want to open with HouseClub app or Chrome
> 3. Click HouseClub and it aks if you want to join room
> 4. Click Join, and room is joined

Right now I don't have link for any active room, maybe this is the reason. But I don't see Houseclub in list of applications, that can handle with this link

<img src="https://user-images.githubusercontent.com/1898310/109013993-ca062500-76c4-11eb-8c8b-a1a6c5f9ab39.jpg" alt="" width="200"/>

**Comment by SaadAssa** [comment]
You can go to clubsearch.io and search for rooms, but the room need to be active (tip: if you go to the bottom of the page, you find the rooms active right now)

**Comment by impozzible** [comment]
@spbroma try this link
https://www.joinclubhouse.com/event/P0Ara849

**Comment by msizaky16** [comment]
Little tips, you can open the link in chrome first, then tap "open the app" from chrome, choose houseclub
It's work for me as well

**Comment by msizaky16** [comment]
Little tips, you can open the link in chrome first, then tap "open the app" from chrome, choose houseclub
It's work for me as well

**Comment by Chepainais** [comment]
If join link starts with www, then it works.
Yesterday i received url without www, and I wasn't able to open it in app..
it's not in supported URL list

**Comment by spbroma** [comment]
I have completely uninstalled and then installed application — and this helped to resolve my issue.

Thanks everyone, who participated with an advice!
