### ISSUE TITLE
I cannot creat a new room and search

### ISSUE THREAD

**Issue by wsboner** [grishka/Houseclub#156]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by oceanchinatownredpie** [comment]
I would like an improvement in it too!

**Comment by SubZero5** [comment]
I would like to see the ability to search too...

**Comment by SaadAssa** [comment]
Same here, also to be able to join clubs

**Comment by vvnniq** [comment]
And me

**Comment by NAN1985** [comment]
😆

**Comment by vvnniq** [comment]
Why closed 😕

في السبت، ٢٧ فبراير ٢٠٢١ ١٢:٥٥ ص Gregory K <notifications@github.com> كتب:
