### ISSUE TITLE
Raise your hand 

### ISSUE THREAD

**Issue by Seerpentin** [grishka/Houseclub#17]
The hand rises only for a couple of seconds, it works very strangely

**Comment by stypr** [comment]
**The code is implemented properly.**

https://github.com/grishka/Houseclub/blob/63d04453e853f3ff5c8df93ae9ee762a4053f40b/Houseclub/src/main/java/me/grishka/houseclub/VoiceService.java#L257-L263

The hand raise notification popup is only shown for several seconds, but the hand is still raised when you check from the actual client.
