### ISSUE TITLE
When invited as speaker , invitation dialog not appear 

### ISSUE THREAD

**Issue by AhmedBahaaAndroid** [grishka/Houseclub#182]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel]
 - OS: [e.g. Android 11]
 - Version [e.g. 1.0.7]

**Additional context**

**Comment by YoussefGoma** [comment]
I quote from user "elzahlan" in a previous issue :
It is a network issue in Egypt, you need to use a VPN to be able to accept invites and go to the speakers area

**Comment by IamHolden98** [comment]
@uosef2111 
when I used a VPN I couldn't hear anything

**Comment by grishka** [comment]
You're supposed to, you know, actually fill in the template.

Anyway, pull requests are welcome.

**Comment by YoussefGoma** [comment]
> @uosef2111
> when I used a VPN I couldn't hear anything

Join another room then get back to the one you wanna to join and it shall work just fine @IamHolden98
