### ISSUE TITLE
UPDATE THE APK!!

### ISSUE THREAD

**Issue by YoussefGoma** [grishka/Houseclub#186]
**Is your feature request related to a problem? Please describe.**
You updated the code, added more features and didn't update the compiled apk file 
**Describe the solution you'd like**
Update the apk
**Describe alternatives you've considered**
None
**Additional context**
None

**Comment by eugene-yang** [comment]
Not speaking on behave of the owner of this repository. 
But this is an active developing project and clearly there are PR being merged. 
I believe @grishka hasn't release a new dot version and apk for some good reason(testing, more PR lining up to merge, etc). 
And I also believe @grishka is not working on this project as a full time job. 

If you really want to use the unstable version, you can pull it down and compile it by yourself. 
The code is there and google is online. 
I would not rush for new apk release.

**Comment by Ahmad90kw** [comment]
@uosef2111, you are very rude first of all he does not work for you this is a platform to show skills. If you want a comolete version of the app as fast as possible then buy an iPhone and stop being rude

**Comment by YoussefGoma** [comment]
I didn't mean to be rude, I'm sorry if you felt so @grishka i liked the project and ithas helped me a lot that's why i was in such a rush to get it updated, i really appreciate your work

**Comment by mkljczk** [comment]
you can clone the repo and build your own or maybe download this one: https://github.com/mkljczk/Houseclub/releases/tag/untagged-2840a14d79b45b04d354
