### ISSUE TITLE
unable to speak as the request approve from moderator not arriving

### ISSUE THREAD

**Issue by AhmdZanoon** [grishka/Houseclub#195]
**Describe the bug**
unable to speak and moderator says that he accepted the request after i raise the hand 

**To Reproduce**
1. Go to 'any room '
2. Click on 'raise hand '
3. observe that mic not appear 

**Expected behavior**
after raising hand 🖐 mic must appear after moderator accept the requeset

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. oppo f11 pro android 10 and androide 11 ]
 - OS: [e.g. Android 11]
 - Version [e.g. 1.0.8

**Additional context**

**Comment by HagarMagdy** [comment]
Using VPN worked for me in this issue

**Comment by AhmdZanoon** [comment]
> Using VPN worked for me in this issue

@HagarMagdy can you recommend an app ?

**Comment by AhmedBahaaAndroid** [comment]
use vpn it's network issue in egypt 
i recommend ProVpn

**Comment by AhmedFadel0393** [comment]
Has anyone solved this bug for Egypt?
I tried VPN and didn't work

**Comment by Ahmad90kw** [comment]
It is arriving for me and working fine, so far have seen no bugs with the app whatsoever and I am persistently on there for hours every day
My device is android Samsung galaxy s10

**Comment by mostafasayed33** [comment]
@AhmedBahaaAndroid is the app still working with you? are you able to hear the audio? because i'm not!

**Comment by OmarKhalifaa** [comment]
@mostafasayed33  Use " Betternet " Vpn it will work .

**Comment by Khaiiryy** [comment]
Ok using vpn will allow you to move to the speakers bt still can't speak

**Comment by Chepainais** [comment]
Refreshing the room helped me. Just pull down top of the page

**Comment by itszakjo** [comment]
Yeah that's because the app relays on pubnub as well , and pubnub is restricted in Egypt , well not actually in Egypt but restricted by WE ISP , So you will have to use Vodafone , Orange or any other ISP , or u could use a VPN , but make sure the VPN opens pubnub.com first , if it does , then you are good to go

**Comment by AhmdZanoon** [comment]
using vpn solved the issue , thanks
