### ISSUE TITLE
Пердящий звук на Samsung s10 android 11

### ISSUE THREAD

**Issue by goitart** [grishka/Houseclub#21]
У всех спикеров звук как будто через ужасный микрофон

**Comment by kavasak119999** [comment]
На Samsumg A30 android 10 идентично. Слушать невозможно

**Comment by Serega11** [comment]
Подтверждаю (Samsung s10+), проработало несколько минут (звук был отличный) , затем начал звучать, как при плохом подключении (трещит )

**Comment by Dippere** [comment]
Samsung a8 plus , звук трещит

**Comment by monono2** [comment]
Galaxy A70, Android 9 - та же хрень

**Comment by anelfer** [comment]
Та же проблема. Realme 6. Звук идет почему-то через разгворный динамик, хотя по логике должен идти через основной.

**Comment by polishary** [comment]
Samsung Galaxy A30, тоже звук будто из старого магнитофона. Как это исправить?

**Comment by CommanderTvis** [comment]
Duplicated by #38

**Comment by dmitryshkinder** [comment]
Samsung a50 такая же проблема

**Comment by CommanderTvis** [comment]
Fixed in the last commit.

**Comment by grishka** [comment]
Fixed in 1.0.4

**Comment by lucidyan** [comment]
@grishka 1.0.4, 1.0.6 - crackling никуда не делся.

**Comment by grishka** [comment]
Ну значит я ничего не могу с этим сделать. Сорян.

**Comment by grishka** [comment]
Наверное, это одна из причин, почему нет официального приложения)

**Comment by lucidyan** [comment]
А расскажи в чём дело, это проблема Agora под Android или чего? Я вот заметил, что проблема плавающая и часто появляется, когда канал плохой (метро, например). Может, это как-то связано с шириной канала, битрейтом и его переключением?
