### ISSUE TITLE
Account has been suspended for violating spam policy

### ISSUE THREAD

**Issue by msizaky16** [grishka/Houseclub#220]
**Describe the bug**
Got notif acc suspended from ofc clubhouse, so i can't do anything. Can't join room, can't see my following/ers [always says "error loading data"]

**To Reproduce**

**Expected behavior**
Fix it please

**Screenshots**
![IMG_20210302_053332_879](https://user-images.githubusercontent.com/79402713/109568327-59726480-7b19-11eb-95b8-b93e7410b84f.jpg)

**Smartphone (please complete the following information):**
 - Device: [Redmi Note 5]
 - OS: [Android 9]
 - Version [1.0.8]

**Additional context**

**Comment by Ahmad90kw** [comment]
This is because you have been spamming the app with either a fake name or with a fake picture and your behavior on app is not normal even if u had a. IPhone this will happen. But this has nothing to do with programming and has nothing to do with Android phones

**Comment by msizaky16** [comment]
I haven't used the app for the last 3 days btw

**Comment by RickCastle2018** [comment]
@Ahmad90kw what are you talking about?! ALL ANDROID USERS WERE BANNED AT 21:00 UTC+3

**Comment by Ahmad90kw** [comment]
Lol so you oversee all android users? I am on the app right now as I am writing and there is nothing wrong with the app at all

**Comment by Ahmad90kw** [comment]
The app is working fine and I know other people who also say that there is nothing wrong with it and I had a look at the spam rules and it shows clearly why would someone be suspended dud to spam etc. It has nothing to do with this build

**Comment by Ahmad90kw** [comment]
Also anyone who uses VPN regardless if it was via iPhone or Android would also get a ban in time
