### ISSUE TITLE
FR: channel language filter

### ISSUE THREAD

**Issue by psydvl** [grishka/Houseclub#24]
Feature request: 
Filter for channels very desired, because now more than half of them are in Chinese.

**Comment by stypr** [comment]
There is no efficient way to filter channels before you start following / adding your interests.

Listing channel does not allow any parameters. (fyi https://github.com/stypr/clubhouse-py/blob/v304/clubhouse.py#L661-L666)

Adding/removing Interest list is done by using following functions

https://github.com/stypr/clubhouse-py/blob/v304/clubhouse.py#L1099-L1124

The value for `topic_id` is hardcoded and there are a lot of topics which are hard to list out each and all.

So I've checked on some of topics that can be used to filter Channels and here's the list. 

You can use this for the implementation

* Chinese: 98
* Japanese: 99
* Hindi: 100
* French: 101
* Spanish: 102
* German: 103
* Arabic: 104
* Russian: 105
* Indonesian: 106
* Portuguese: 166

**Comment by Blackwolf14** [comment]
> There is no efficient way to filter channels before you start following / adding your interests.
> 
> Listing channel does not allow any parameters. (fyi https://github.com/stypr/clubhouse-py/blob/v304/clubhouse.py#L661-L666)
> 
> Adding/removing Interest list is done by using following functions
> 
> https://github.com/stypr/clubhouse-py/blob/v304/clubhouse.py#L1099-L1124
> 
> The value for `topic_id` is hardcoded and there are a lot of topics which are hard to list out each and all.
> 
> So I've checked on some of topics that can be used to filter Channels and here's the list.
> 
> You can use this for the implementation
> 
> * Chinese: 98
> * Japanese: 99
> * Hindi: 100
> * French: 101
> * Spanish: 102
> * German: 103
> * Arabic: 104
> * Russian: 105
> * Indonesian: 106
> * Portuguese: 166

I live in Turkey. How can I do this? I am not a developer. I've started to following/adding my interest but still more than half of them are in Chinese, Russian, Thai.
