### ISSUE TITLE
Profile pic upload

### ISSUE THREAD

**Issue by mnb3000** [grishka/Houseclub#26]
Currently the only thing that is not possible through the clubhouse-py app - is the profile pic upload. Do you plan on reversing the process of the upload? (I guess it must be some kind of S3 bucket, but I dunno)

**Comment by stypr** [comment]
It's been already reverse engineered, it's just you didn't check the code properly. I've left the comment on my repo.

https://github.com/stypr/clubhouse-py/issues/7

**Comment by CommanderTvis** [comment]
Duplicate of #12

**Comment by mnb3000** [comment]
Closing as a duplicate of #12
