### ISSUE TITLE
If you are in the audience you can't get up to the voice chat ever

### ISSUE THREAD

**Issue by youssefsroor** [grishka/Houseclub#264]
**Describe the bug**
When you raise your hand and the mods accept it you can't get up to the voice chat section

**To Reproduce**
1. Go to 'any room'
2. Click on 'the wave or raise hand'
3. Scroll down to 'voice chat members'
4. You are not there and can't get up in the voice chat section ever when the mods accept your raise

**what you expected to happen**
I expected to simply join the voice chat members 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [ L.G V20 ]
 - OS: [ Android 8 ]
 - Version [ 1.0.9 ]

**Additional context**

**Comment by AmirEltagory** [comment]
Use vpn

**Comment by youssefsroor** [comment]
> Use vpn

It didn't work either 
I can't get up and Still stuck on the hand emoji don't even turn to the Mice one

**Comment by ghost** [comment]
Change dns to 1.1.1.1
And it will work 
Or use 1111 vpn

**Comment by youssefsroor** [comment]
![Capture+_2021-03-12-15-33-44](https://user-images.githubusercontent.com/80293941/110947190-81976a00-8348-11eb-8f09-57fca65a1913.png)
This is what i mean there is no mice icon and cant join the others above

**Comment by ghost** [comment]
Don't use your vpn service just use this one instead and it should work

https://play.google.com/store/apps/details?id=com.cloudflare.onedotonedotonedotone

After using it close the app and open it again

And after you got invited refresh the app by swiping done the screen and you should see the mic icon

**Comment by youssefsroor** [comment]
It worked very well, thanks

**Comment by kiro12kiro** [comment]
How can i get 1.0.9 version?

**Comment by youssefsroor** [comment]
https://github.com/bit-world/Houseclub/releases/tag/1.0.9
