### ISSUE TITLE
No support for bluetooth headsets

### ISSUE THREAD

**Issue by skiezest** [grishka/Houseclub#27]
After connecting a bluetooth headset to the phone the sound keeps playing from the speaker.

**upd. Workaround: Restart the app**

**Comment by anbrikzone** [comment]
The same problem if plug in wire headset. Sound still goes from speaker. OnePlus 7, Android 10, version app: 1.0.2

**Comment by skiezest** [comment]
Oh so it has actually worked, idk why. Seems like you need to restart the app in order for it to work

**Comment by anbrikzone** [comment]
> Oh so it has actually worked, idk why. Seems like you need to restart the app in order for it to work

Yep, you are right. Needed to restart.
