### ISSUE TITLE
Search clubs and join it 

### ISSUE THREAD

**Issue by acalyxs04** [grishka/Houseclub#273]
Hello people! First of all, thank you for the incredible work you have done together. The effort behind the project is greatly appreciated. They have done an exceptional job! So he congratulated all the contributors and especially grishka for his enormous effort in bringing the possibility of having access to clubhouse with Android. Excellent! Thanks I have this request to ask, if it is possible to add the option to search for clubs, I do not know anything about programming, and I do not know if it is a lot of work ... I apologize if what I ask is very difficult, and I understand that the version will be available soon official, and maybe not worth working on ... anyway, thanks people, you are amazing!

**Comment by tarbindmitry** [comment]
hello, friend!
thank you!
look, we need one more invite!
send yours (or someone) invite for our russian friend.
his number is +79269003509

сб, 13 мар. 2021 г. в 05:07, edson69 ***@***.***>:
