### ISSUE TITLE
CAN'T LOGIN!!

### ISSUE THREAD

**Issue by Sundossalhin** [grishka/Houseclub#285]
Guys, I joined a room and when I raise my hand to speak they couldn'tgive me the microphoneor be on stage! They asked me to go out n rejoin, I did but I couldn'tspeak, so I thought if I uninstalled the app and re install it will be able to speak, but when I did I couldn'teven log in with my number!!! 
I tried many times!

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: [e.g. Google Pixel]
 - OS: [e.g. Android 11]
 - Version [e.g. 1.0.7]

**Additional context**

**Comment by Hesham942** [comment]
Use vpn

**Comment by houska85** [comment]
You have blocked access. The application is missing an error: We are unable to sign you in. Please try again later.
