### ISSUE TITLE
Cannot log in 

### ISSUE THREAD

**Issue by Sundossalhin** [grishka/Houseclub#286]
**Describe the bug**
Can't log in to my houseclub account anymore!!

**Smartphone (please complete the following information):**
 - Device: Samsung S9 plus
 - OS: [e.g. Android 11]
 - Version [e.g. 1.0.7]

**Additional context**
Guys, I joined a room and when I raise my hand to speak they couldn'tgive me the microphoneor be on stage! They asked me to go out n rejoin, I did but I couldn'tspeak, so I thought if I uninstalled the app and re install it will be able to speak, but when I did I couldn'teven log in with my number!!! 
I tried many times!

**Comment by Sundossalhin** [comment]
Guys, I used a VPN app to speak and It worked.

**Comment by Hassanalsafi** [comment]
Describe the bug
Can't log in to my houseclub account anymore!!

Smartphone (please complete the following information):
Device Huawei nova 3
Os android 11
