### ISSUE TITLE
Не понятно как выключить микрофон в комнате 

### ISSUE THREAD

**Issue by skylark71** [grishka/Houseclub#31]
Когда захожу в комнату микрофон включен постоянно, не понятно как его отключить 🦧 Можно было б выключить микрофон было б идеально 🙌
Спасибо большое за приложение 🤗

**Comment by skylark71** [comment]
> микрофон

Я разобрался 🙌 Но иногда значок выключить микрофон не появляется, остаётся значок 🖐️

**Comment by grishka** [comment]
Кнопку с микрофоном нажать. Тут вообще-то не техподдержка.
