### ISSUE TITLE
Я установила приложение, но почему то не могу получить инвайт не приходит смс((

### ISSUE THREAD

**Issue by alechur1yandexru** [grishka/Houseclub#32]

**Comment by alechur1yandexru** [comment]
Можете подсказать что не так?

**Comment by tossha** [comment]
Другой человек должен пригласить вас по номеру телефона из iOS-приложения. Если он вас пригласил, то SMS придёт.

**Comment by alechur1yandexru** [comment]
> Другой человек должен пригласить вас по номеру телефона из iOS-приложения. Если он вас пригласил, то SMS придёт.

Hey - Did you get my Clubhouse invite? I added +972505577754, so if you use that # you can skip the waitlist. Here is the link:

https://join.club/app

мне приходит вот эта ссылка на аппстор и все

**Comment by tossha** [comment]
Зайдите в приложение и зарегистрируйтесь по этому номеру. При возникновении проблем перезапустите приложение.

**Comment by grishka** [comment]
Когда вам кто-то даёт инвайт, ничего не приходит. Надо просто перезапустить приложение, оно само поймёт, что дали инвайт, и предложит заполнить имя и юзернейм.

Лучше на эту тему тут не оффтопить.
