### ISSUE TITLE
вижу только арабские комнаты

### ISSUE THREAD

**Issue by midnightdaughter** [grishka/Houseclub#34]
не вижу русских комнат, только одну
остальные все арабские. как изменить?

**Comment by tossha** [comment]
Это не баг. В описании сказано, что сейчас отображаются лишь рекомендуемые сервером комнаты. Вы можете переходить в комнаты по ссылкам вида /room/XXXX. Ссылки вида /events/XXXX сейчас не работают.

**Comment by rustamsmax** [comment]
У кого нибудь инвайт есть? )

**Comment by HighVoltageLP** [comment]
сейчас висят Материнство и самореализация и Адекватный феменизм, залетай

**Comment by grishka** [comment]
Это не проблема приложения.
