### ISSUE TITLE
По-прежнему не работают инвайты приложение даже переустановила заново

### ISSUE THREAD

**Issue by alechur1yandexru** [grishka/Houseclub#37]
Он пишет, что мой аккаунт неактивен хотя уже три человека сделали инвайты и я его перезапускала

**Comment by alechur1yandexru** [comment]
что может быть не так? телефон редми

**Comment by HighVoltageLP** [comment]
на сяоми только что тестил, пригласили и все заработало

единственная русскоязычная группа на экране - материнство и самореализация, там и сижу

**Comment by oceantiee** [comment]
Только что пригласили, зарегался, всё нормально. Жаль сам не могу инвайты отправить теперь

**Comment by CommanderTvis** [comment]
@oceantiee #18

**Comment by eovin991** [comment]
Самсунг, полёт нормальный.

**Comment by combrs** [comment]
> Он пишет, что мой аккаунт неактивен хотя уже три человека сделали инвайты и я его перезапускала

когда "делают инвайты", то должна прийти смс, где написано "Hey, did you get my Clubhouse invite?"
после того как я ее получил, я просто зашел в приложение и продолжил регистрацию.
Если такое смс не пришло, значит "три человека" сделали что-то не так.

**Comment by alechur1yandexru** [comment]
> > Он пишет, что мой аккаунт неактивен хотя уже три человека сделали инвайты и я его перезапускала
> 
> когда "делают инвайты", то должна прийти смс, где написано "Hey, did you get my Clubhouse invite?"
> после того как я ее получил, я просто зашел в приложение и продолжил регистрацию.
> Если такое смс не пришло, значит "три человека" сделали что-то не так.

А вы не могли бы прислать инвайт? Тел +9720505577754 я просто даже не понимаю что они все сделали не так((

**Comment by combrs** [comment]
> А вы не могли бы прислать инвайт? Тел +9720505577754 я просто даже не понимаю что они все сделали не так((

нет, в этом приложении не реализована работа с инвайтами (пока?)
я через канал в телеграме получал  - Через @clubhouse_invite_ru
