### ISSUE TITLE
Audio continuously crackles

### ISSUE THREAD

**Issue by PGlynn** [grishka/Houseclub#38]
When joining the first room after install, audio works fine.  After changing rooms, audio is crackling and distorted.  This persists even if the original room is rejoined or if the app is restarted.

**Comment by vatson** [comment]
@PGlynn as a temporary workaround you can try to clean the cache of application and re-open. It works for me. But it's really annoying

**Comment by raphaelnew** [comment]
Samsung Galaxy S21 Ultra crackles in any chat you join...

**Comment by andriy2** [comment]
Pixel 4, sound crackles happens only when app is in background (+ screen is off)

**Comment by CommanderTvis** [comment]
Reproduced on Samsung Galaxy J7&mdash;the app should be in the background
