### ISSUE TITLE
Not installing on Android 10

### ISSUE THREAD

**Issue by wileyfoxyx** [grishka/Houseclub#4]
Can't install the app on Android 10.

Device: Samsung Galaxy A01 SM-A015F/DS
OS; Android 10 (One UI 2.0)

**Comment by DenisNP** [comment]
@wileyfoxyx please, add more info. Can you install other custom apk's? What happens when you are trying? Maybe some screenshots too.

**Comment by wileyfoxyx** [comment]
> Can you install other custom apk's?

Yes, I can.

> What happens when you are trying?

Progress bar are showing for a second and then appearing "App is not installed".

**Comment by wileyfoxyx** [comment]
UPD. Now it works if install 1.0.1-fix.
