### ISSUE TITLE
Error loading data

### ISSUE THREAD

**Issue by skaitrip** [grishka/Houseclub#48]
Телефон: Xiaomi Mi 9 Lite

Получилось зарегистрироваться, дали инвайт со стороны. Но не могу завершить регистрацию, введя имя и т.д. Постоянная ошибка "Error loading data".
После перезапуска приложения доступны комнаты, могу заходить. Но страница профиля все время выдает ошибку загрузки данных. 
Друзья с айфонов тоже не видят меня.

**Comment by anabsh05** [comment]
Попробуйтебез пробела имя свое сделать, если вдруг с пробелом из двух слов.

**Comment by skaitrip** [comment]
Спасибо ща совет!
Имя в одно слово. Я могу заполнить поля, но дальше приложение выдает ошибку "Error loading data".
Если закрыть приложение и зайти снова, то он открывается нормально. Есть лента с актуальными комнатами. 
Но, друзей своих я не вижу, как и она меня.
Если зайти на страницу профиля, то там будет та же ошибка: "Error loading data" и кнопка "Reply", нажатие на которую ничего не даёт.

**Comment by skaitrip** [comment]
Также, заметил еще один баг. Заходя в комнату, звук сначала нормальный, но со временем становится с помехами. Как тут народ пишет "пердящий". Чем дольше находишься в комнате, тем хуже становится звук.
