### ISSUE TITLE
any tips for joining room via direct link?

### ISSUE THREAD

**Issue by msizaky16** [grishka/Houseclub#54]
how to join room channels via link?
ex: https://www.joinclubhouse.com/event/A1b2c3D4

**Comment by grishka** [comment]
Uh? Open the link. Click the button. Choose "Houseclub".

**Comment by msizaky16** [comment]
it does'nt work, just showing 2 browsers app on my phone not Houseclub app. Any tips?
try to reinstall it and not affected at all
using redmi note 5 with miuiroom
