### ISSUE TITLE
Не открывает никакие ссылки на комнаты и ивенты

### ISSUE THREAD

**Issue by AntonMinaev** [grishka/Houseclub#55]
в 1.0.3
Android 10, чистый
moto one action

Пробовал убирать ios в урле, всё равно не получатеся. Из фф, из хрома, из маленьких фф и хрома тоже.
В прошлых версиях тоже не открывал.

Как вариант, сделать открытие через шейр из браузера в приложение.

**Comment by AntonMinaev** [comment]
Только что, почти удалось из хрома. Ссылка из твиттера, повела на адрес без поддомена "ios", с "www". Если добавить "ios" - ничего, если убрать "www" и оставить "ios" предложило открыть через приложение, но после процессинга выдало "Error loading data"

**Comment by grishka** [comment]
Исправлена ошибка с открытием ссылок на /event/, а так надо нажать "open in app" в шапке на сайте.
