### ISSUE TITLE
direct link "error loading data"

### ISSUE THREAD

**Issue by KaizerHanz** [grishka/Houseclub#59]
as we can't search room, I hope can we can join using direct link, in my case when I get direct link have "error loading data". I hope can fix in the next update.

**Comment by Aduhelm** [comment]
Same error on Oneplus 8.

**Comment by msizaky16** [comment]
same error on redminote 5

**Comment by levchig** [comment]
Same error xiaomi mi 9 lite

**Comment by plykung** [comment]
I also has the same error. 
I think that this error came from the fact that <event_hashid> from www.joinclubhouse.com/event/<event_hashid> is not the same as <channel_name> from www.joinclubhouse.com/room/<channel_name> which you can use to connect to the channel directly.  I suggest that you can fix this error by retrieving <channel_name> from <event_hashid> first.

I am not sure how to do it in java. But in python (based on stypr/clubhouse-py), you can use event_data = Clubhouse.get_event(event_hashid=<event_hashid>) and then get <channel_name> from channel_name = event_data['event']['channel'] before connecting to the channel.

Hope this error can be fixed soon!

**Comment by grishka** [comment]
Ah so events and channels are different things after all.

**Comment by royshengelia** [comment]
@grishka, Yeap to start https://www.joinclubhouse.com/event/ID working you should grub channel_name for that.

**Comment by grishka** [comment]
Can I have an example link to test?

**Comment by royshengelia** [comment]
@grishka Sure, Here you go: https://www.joinclubhouse.com/event/VMR2qYMD

BTW - Thank you, Nice Job. Спасибо =)

**Comment by royshengelia** [comment]
@grishka One more - https://www.joinclubhouse.com/event/xjY9LOAN This one will start in half-hour.

**Comment by grishka** [comment]
Interesting. I'm sending `get_event` with `event_hashid` but I get a 500 error.
