### ISSUE TITLE
Как открыть ссылку на беседу?

### ISSUE THREAD

**Issue by mccakestd** [grishka/Houseclub#67]
Вопрос в тайтле. Жму на ссыль, открывает заглушку, что скачай ка ты прогу для Айоса. Закинул в блокнот ссыль - для открытия показывает лишь мой браузёр. Как я вижу в ЧаВо, клиент работает со ссылками.

**Comment by grishka** [comment]
"Open in app" в шапке страницы тоже не работает?

**Comment by royshengelia** [comment]
@mccakestd , Попробуйте открыть с помощью Google Chrome.

**Comment by mccakestd** [comment]
> "Open in app" в шапке страницы тоже не работает?

Попробовал, пишет error loading data. Возможно беседа закрыта.

**Comment by royshengelia** [comment]
@mccakestd , Можете дать ссылку? Проверю.

**Comment by mccakestd** [comment]
> @mccakestd , Можете дать ссылку? Проверю.

https://www.joinclubhouse.com/event/xpjlzVeg

**Comment by royshengelia** [comment]
@mccakestd , Это Event, а не Channel.
https://www.joinclubhouse.com/event/ - Event
https://www.joinclubhouse.com/room/ - Channel 

Пока войти в Event с помощью этого приложения невозможно.
Проблема обсуждается здесь #59

**Comment by grishka** [comment]
Исправлено в новом апк
