### ISSUE TITLE
cant open mic

### ISSUE THREAD

**Issue by kjedottisu** [grishka/Houseclub#68]
i tried this apk, i can join room, but i cant voice

**Comment by ghost** [comment]
Yeah, the same shittt
![Безымянный](https://user-images.githubusercontent.com/72400092/108631981-a7ce9600-747d-11eb-89e9-3306a57a9405.png)

**Comment by grishka** [comment]
Do you even understand how clubhouse works?!

You join a room. You can only listen. You raise your hand. A moderator accepts it. An alert pops up asking if you want to become a speaker. You accept. You can now speak.

**Comment by magedfam** [comment]
@grishka i get invited and i don't get the alert pops up asking if you want to become a speaker
