### ISSUE TITLE
Вход в комнату по прямому линку

### ISSUE THREAD

**Issue by indigo256** [grishka/Houseclub#7]
Вход через ссылку не работает. Просто открывается веб

**Comment by anchar2k** [comment]
Да, не распознает ссылки вида https://ios.joinclubhouse.com/event/<some_id>
Сейчас есть открытие в приложении https://ios.joinclubhouse.com/room/<some_id>, но я не понимаю в чем отличие между event и room

**Comment by Viktor2004** [comment]
Очень не хватает. Очень хочется на ряд ивентов попасть

**Comment by archonoff** [comment]
@grishka Будь котиком, пересобери апк в разделе релизов. Не хочется ради этого студию ставить.
