### ISSUE TITLE
Не открывает приложение из Телеграмм

### ISSUE THREAD

**Issue by menand** [grishka/Houseclub#72]
Не открывает приложение (соответственно не возможно войти в комнату) при переходе по ссылке в телеграмме вида https://www.joinclubhouse.com/event/MzEnVanR

PS если ссылку в браузер вставить или отсюда нажать - всё равно ничего не получается.

На версии 1.0.5

**Comment by grishka** [comment]
Open in app

**Comment by SurPaul** [comment]
Раньше после нажатия на кнопку «Open in app» ничего не происходило, а сейчас она и вовсе пропала. Даже настройки открытия ссылок менял:

![Screenshot_Chrome_20210222-000934](https://user-images.githubusercontent.com/1708881/108637054-5b498180-74a2-11eb-985d-214972624ef2.png)![Screenshot__20210222-000955](https://user-images.githubusercontent.com/1708881/108637055-5c7aae80-74a2-11eb-819a-098ce7eaa454.png)

**Comment by menand** [comment]
> Раньше после нажатия на эту кнопку я с[Screenshot__20210222-000955](https://user-images.githubusercontent.com/1708881/108637055-5c7aae80-74a2-11eb-819a-098ce7eaa454.png)

А где вы нашли вот это "открывать ссылки"?

**Comment by SurPaul** [comment]
> > Раньше после нажатия на эту кнопку я с[Screenshot__20210222-000955](https://user-images.githubusercontent.com/1708881/108637055-5c7aae80-74a2-11eb-819a-098ce7eaa454.png)
> 
> А где вы нашли вот это "открывать ссылки"?

«Настройки» → «Приложения и уведомления» → «Houseclub» → «Дополнительно» → «Открывать по умолчанию».
