### ISSUE TITLE
Хрипы версия 1.0.6

### ISSUE THREAD

**Issue by w432w** [grishka/Houseclub#83]
Хрипящий звук на версии 1.0.6
Телефон Alcatel 1S (2019)  5024D Android 9.

**Comment by anbrikzone** [comment]
Аналогично, OnePlus 7, Android 10

**Comment by SurPaul** [comment]
LeEco Le 2, Android 9

**Comment by Denisiuz** [comment]
Galaxy Note 9, хрипы через Bluetooth TWS Galaxy Buds, Android 10

**Comment by grishka** [comment]
Да достали. Я понятия не имею почему эти ваши хрипы.
