### ISSUE TITLE
Create Room & Search Rooms

### ISSUE THREAD

**Issue by BexDevs** [grishka/Houseclub#87]
Hi,
Can I create and search Roms in this porting?

**Comment by vatson** [comment]
Searching is not even supported by official client

**Comment by SaadAssa** [comment]
You can go to the website clubsearch.io and search for rooms and click on the join link. With the latest version, you can open links into the app.

**Comment by BexDevs** [comment]
Tka... for create one

**Comment by SaadAssa** [comment]
@iPaky95 ? what do you mean (what is tka)?

**Comment by BexDevs** [comment]
Thanks.... sorry
How can I create a rom?

**Comment by SaadAssa** [comment]
Oh ok. We can't currently create or moderate rooms (I think), but you can search for a room you like on clubsearch.io and you can follow users to receive more accurate suggestions of rooms by the app. You can always ask one of your friends to create a room and join it.

**Comment by BexDevs** [comment]
Ok Thank for support ... Great Wok

**Comment by SaadAssa** [comment]
No problem!
