### ISSUE TITLE
Не даёт начать говорить в комнате

### ISSUE THREAD

**Issue by Jazzslideshow** [grishka/Houseclub#9]
Заходит в комнату без проблем, но когда модератор даёт право слова, то на моем экране ничего не отображается, и стать спикером не могу. Кнопка "поднять руку" прожимается, но какого-то эффекта вроде бы нет

**Comment by Spar9a** [comment]
Аналогичная проблема.

Устройство huawei p30 pro

**Comment by grishka** [comment]
Там pubnub сломался... Вчера работало, а сегодня снова 403.

**Comment by CommanderTvis** [comment]
Same issue

**Comment by CommanderTvis** [comment]
@grishka re-open, please
