### ISSUE TITLE
Не получилось стать спикером. Меня не слышали.

### ISSUE THREAD

**Issue by eovin991** [grishka/Houseclub#91]
Сегодня несколько часов слушала других спикеров. Слышимость отличная. 1.0.5. 
Тел Samsung N975F Android 11
Когда попала в спикеры, появился справа микрофон. По нажатию вроде включался-отключался. Но когда мне дали слово, включив микрофон меня не слышали. Жаль, надеялась поболтать.

**Comment by grishka** [comment]
1.0.5 не последняя версия, обновитесь

**Comment by eovin991** [comment]
> 1.0.5 не последняя версия, обновитесь

Спасибо, уже вижу.)
