### ISSUE TITLE
Join a club

### ISSUE THREAD

**Issue by SaadAssa** [grishka/Houseclub#97]
Hi, how can I search for rooms (usings keywords or subjects)? Is it possible to add this feature to Houseclub? If it isn't possible, we could search for rooms using tools like clubsearch.io or findclubhouse.com but when we click on the link to join the event, the event isn't opened in the app...

In short: 
-Is it possible to add a feature to search for rooms?
-How can we open the link of a Clubhouse event in Houseclub?

Thanks!

**Comment by SaadAssa** [comment]
Hi, sorry I now installed the latest version of Houseclub and I can open links correctly. I'm curious, is it possible to add a search feature on the app (like clubsearch.io did)?

**Comment by SaadAssa** [comment]
Also, to avoid making another issue thread, I'll post my other question here: is it possible to join a Club on Houseclub?

**Comment by mahasenovic** [comment]
How can you open link ? 
It's not working with me !

**Comment by SaadAssa** [comment]
@mahasenovic you need to install the latest version of the apk, then simply open the link on your browser. But the room needs to be active, if you put the link of a closed room, you'll be redirected to the website of clubhouse.

**Comment by d0nn13** [comment]
I had to add the missing `www` to the link for it to work.
